name: nn-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python<3.13
  - shap
  - tensorflow
  - pip
  - matplotlib
  - seaborn
  - pip:
      - torch
      - torchvision
      - torchaudio